//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_critica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaDeCriticaBDEntities1 : DbContext
    {
        public SistemaDeCriticaBDEntities1()
            : base("name=SistemaDeCriticaBDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<ComentarioSet> ComentarioSet { get; set; }
        public virtual DbSet<Noticias> Noticias { get; set; }
        public virtual DbSet<Reseña> Reseña { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
