//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_critica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reseña
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reseña()
        {
            this.ComentarioSet = new HashSet<ComentarioSet>();
        }
    
        public int IdReseña { get; set; }
        public string titulo_reseña { get; set; }
        public string contenido_reseña { get; set; }
        public Nullable<decimal> puntuacion_reseña { get; set; }
        public System.DateTime fecha_reseña { get; set; }
        public int UsuarioId { get; set; }
        public int Categoria_IdCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentarioSet> ComentarioSet { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
